### ISSUE TITLE
Does this allow for new systemd support?

### ISSUE THREAD

**Issue by WSLUser** [Biswa96/initrdg#2]
Until I get some time to thoroughly test, I was wondering if this project has been updated to reflect back the changes to init as WSL2 now no longer is using init but allowing native linux with systemd now with it's own daemon as was anticipated if systemd support ever came, which finally it has. Since we download the preview directly from wsl github, those changes are technically getting included and of course want to see a version that allows for this new support unless you determined that something specific to Win11 is required to get it working (but you've already reverse engineered most of WSL already so new bits with Win11 hopefully are easy to determine for you.

**Comment by Biswa96** [comment]
I am not sure about that. I have not dig into that part yet. This project only tries to play with the initrd.img part. Many initialization part are also in init binary which is big.

**Comment by Biswa96** [comment]
Can you provide any info about what the issue was with this first systemd workaround available years ago?

```
sudo daemonize /usr/bin/unshare -fp --mount-proc /lib/systemd/systemd --system-unit=basic.target 
```

It was given in the WSL's systemd issue by therealkenc

**Comment by WSLUser** [comment]
that was the workaround. that isn't needed anymore (at least not for win11 users). A new namespace is created with which systemd could be run. Now wsl init doesn't exist anymore. All wsl specific stuff was moved to become it's own daemon which is run by systemd and init provided by distribution. Basically you might need a new project at this point to account for the latest wsl since all the wslg stuff should of been moved with the other wsl functions to that new daemon. So the process for getting wslg to run on win10 will likely have changed.

**Comment by Biswa96** [comment]
It is not possible to use systemd in Win10 like Win11. Because the init binary checks its pid == 1. Otherwise the init binary does other stuff e.g. wslpath, mount.drvfs etc.

So, if we only care about _pid namespace_ then the above command may help. If the daemonize command is run systemd will start a sshd server in WSL2. Then ssh into that WSL2, you'll get systemd as pid 1. Here is the output after ssh-ing into WSL2.

```
$ cat /proc/1/cmdline
/lib/systemd/systemd--system-unit=basic.target
```

**Comment by WSLUser** [comment]
Guess I can close this if Win10 users can now use the WSL provided as is. It may still be worthwhile having this project and the other one as I know I for one added a couple of features that were removed or pending from wslg (stopping processes that failed several times and allowing Windows fonts to be selectable.)

**Comment by Biswa96** [comment]
I will maintain this project to implement several things which inbox WSL does not support. For example,
1. Mounting /tmp, /var/tmp etc. as tmpfs.
2. Using read-only VHDX file as distribution.
3. Custom network configuration.
4. Little busybox like thing in initrd.
etc.
Not implemented yet, BTW :)
